### ISSUE TITLE
Mistake in "registeration" word

### ISSUE THREAD

**Issue by yariksav** [adonisjs/adonis-persona#10]
I suppose method registerationRules and its description has a mistake in name
registeration instead registration
https://github.com/adonisjs/adonis-persona/search?q=registeration&unscoped_q=registeration

**Comment by RomainLanz** [comment]
PR? 🤗

**Comment by yariksav** [comment]
https://github.com/adonisjs/adonis-persona/pull/12

**Comment by RomainLanz** [comment]
Cool!
Closing in favor of the PR.
