### ISSUE TITLE
2FA Support

### ISSUE THREAD

**Issue by herenickname** [adonisjs/adonis-persona#14]
add to the module the generation and support of 2fa codes

**Comment by RomainLanz** [comment]
There's plenty of third-party services to support 2FA.

**Comment by herenickname** [comment]
yes, but integrating one of them inside the module would be cool

**Comment by RomainLanz** [comment]
Since we don't want any hard dependence of third-party service we will not add that into this module.

Feel free to use any other third-party service you want.
