### ISSUE TITLE
Problem when not using email instead of uid

### ISSUE THREAD

**Issue by rbartholomay** [adonisjs/adonis-persona#17]
Hi there,

currently i play with persona an get some small problem

in the config i defined:

`  uids: ['email'],`

When i try to login i always get an error like "Undefined binding(s) [...]"

i look in the code and found follwing:

```
  async verify (payload, callback) {
    await this.runValidation(payload, this.loginRules(), 'verify')
    const user = await this.getUserByUids(payload.uid)    /// REALLY payload.uid???

    const enteredPassword = this._getPassword(payload)
    const userPassword = this._getPassword(user)

    if (typeof (callback) === 'function') {
      await callback(user, enteredPassword)
    }

    await this.verifyPassword(enteredPassword, userPassword)

    return user
  }
```

i think the problem is the hardcoded payload.uid above?

**Comment by RomainLanz** [comment]
Hey @rbartholomay ! 👋 

Simply rename your `email` field as `uid`.

**Comment by rbartholomay** [comment]
i change the line to 

>     const user = await this.getUserByUids(payload[this.config.uids])

not fully tested

**Comment by RomainLanz** [comment]
I mean, instead of having `{ email: 'john.doe@example.com' }` use `{ uid: 'john.doe@example.com' }`.

```js
const payload = request.only(['uid', 'password'])
const user = await Persona.verify(payload)
```

In this example, `uid` could be a username or an email.

**Comment by rbartholomay** [comment]
yes, I know...  :smile:

I read the comments in the config and thought that all uids defined in the array are accepted on the (post) - request.

thank you for clarifying!

```
  /*
  |--------------------------------------------------------------------------
  | Uids
  |--------------------------------------------------------------------------
  |
  | An array of fields, that can be used to indetify a user uniquely. During
  | login and reset password, these fields be checked against the user
  | input
  |
  */
  uids: ['email'],
```

**Comment by RomainLanz** [comment]
Yes, it's a database field.

Do you mind creating a PR to clarify this in the docblock?

**Comment by rbartholomay** [comment]
no, the problem is my bad english 😆 

I read the block again and now its clear "... against the user input"...

Thank your very much for your help!
