### ISSUE TITLE
Managing Hached email

### ISSUE THREAD

**Issue by VeroniqueGaudrat** [adonisjs/adonis-persona#21]
It would be great to have an option in the connection process that enables to use hached email. I work on a game where gamer should be anonymous. This part of the principle as the population we are targeting is very skeptical regarding marketing.
Therefor I need a connection system where the email is hached. If the length of the hached key is sufficient we have almost no probability of contention (2 different emails giving the same hached key). I did it in a previous project, we kept the hached email in the databse, the gamer give his email, we hache it and we compare the hached values. To recover his password he should give is email that we use for the recovering process.

**Comment by thetutlage** [comment]
Way beyond the scope of this repo. It should be part of your application logic and not a generic library like this

**Comment by thetutlage** [comment]
Closing since not actionable
