### ISSUE TITLE
Generate token that is valid longer than 24h

### ISSUE THREAD

**Issue by rhwilr** [adonisjs/adonis-persona#24]
When I create a new user in my application I use `Persona.generateToken(user, 'password')` and send the token to the user via mail. The user can then set their initial password via the password reset route.
But I want the token to be valid for longer than 24h.

https://github.com/adonisjs/adonis-persona/blob/b28c5231c4355f8a11a2e357e90807ffd77ab70b/src/Persona.js#L156-L161

The constraint is static and added when checking the token, but also used in `generateToken` to check if a token already exists. I wanted to submit a PR that adds a `validUntil` property, but I would have to pass it in multiple places (when generating and when checking).

I'm wondering if it is the right approach to use the `updated_at` field to check if a token is valid of if we should add a `valid_until` field? This way we can define the duration a token is valid when generating it and use different durations for different tokens.

**Comment by thetutlage** [comment]
I believe we can expose a config variable `validUntil` to define the validity of the token in hours. I am happy to accept a PR for same

**Comment by rhwilr** [comment]
But this would change the validity for all tokens in the app. And I would have the change the setting depending on the token I'm validating.

So for my use case, I want the initial "account created" token to be valid for 10 days. But I think it is a good idea to have the "password-reset" token to be only valid for 24h.

I see that it is not easy to change the existing database schema, but it might is worth a thought for the next version?

**Comment by rhwilr** [comment]
I started work on the PR, but I have to say I'm really not happy with it so far. The main problem is that we are misusing the `updated_at` field. 

But we could achieve different validity per token with a little trick. We could set the `updated_at` field to a time in the future, e.g. +48h. This way we could define the duration when generating the token and not when validating it.

**Comment by thetutlage** [comment]
@rhwilr I believe, we are not misusing `updated_at`. The meaning of updated at is when was the last time this row was updated.

If you put a date which is in future, then it will be misuse. What you are looking for is `expires_at` and not `updated_at`

**Comment by rhwilr** [comment]
@thetutlage I'm sorry, I should have specified more clearly. What I mean is that we are using the `updated_at` field to check if a token is valid or not. For me, that is kinda defeating the purpose of this field.

But you're right, I am looking for an `expires_at` field. We would have to add this to the [token migration](https://github.com/adonisjs/adonis-fullstack-app/blob/develop/database/migrations/1503248427886_token.js) and users currently using this package would have to add it themselves.

If I were to submit a PR to change this, would you be willing to accept it?

**Comment by RomainLanz** [comment]
Go for it @rhwilr!

**Comment by RomainLanz** [comment]
Closing in favor of the PR.
