### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by niallobrien** [adonisjs/adonis-persona#29]
Hi - just wondering if this project is still actively maintained and if it's the default Adonis go-to solution for user management?

Thanks in advance.

**Comment by RomainLanz** [comment]
Hey @niallobrien! 👋 

Of course it is.

Note that there's no point of updating a working code, it's not because there was no push in the last months that a project is inactive nor production ready. 😉

**Comment by jamesst20** [comment]
@RomainLanz 

May I ask again if it is still supported ? As you said it might not need updates if it works fine, but it has been over a year.

Also, is it (or will it) be compatible with AdonisJS 5 that is currently in preview version?

**Comment by thetutlage** [comment]
Yes. We will get back to this package and make it ready for v5. But not part of the roadmap right now. I remember @mcsneaky has some ideas around making it ready for v5
