### ISSUE TITLE
Return forgot password token

### ISSUE THREAD

**Issue by elegisandi** [adonisjs/adonis-persona#41]
I have this project that registers new users without a password but has email verification. Once verified, it triggers Persona's `forgotPassword` so the user could set his account's password. Then it will redirect to a new password form, passing the token. But using `forgotPassword` method won't return any value, so I just run a relationship query to grab the token.

It would be awesome if `forgotPassword` could somehow return the token and the user values.

Cheers =)

**Comment by thetutlage** [comment]
What's the use case for getting the token back and the user values?

**Comment by elegisandi** [comment]
@thetutlage use case is mentioned above. but to make it clearer, I need to use the returned `token` to redirect user to a form immediately instead of listening to the event and send an email for example.

the `token` will be passed to the redirect url _(eg: /reset/password/{token})_

hope that makes sense :)

PS: returning the `user` would be a nice to have too.

**Comment by elegisandi** [comment]
i think my concern has already been resolved.
