### ISSUE TITLE
tokens still remains after email verification.

### ISSUE THREAD

**Issue by 9636565** [adonisjs/adonis-persona#5]
In documentation it says  verifyEmail removes the token from the tokens table but it isn't.

After calling await Persona.verifyEmail(token) "account_status" changes to "active" but token still remains in the tokens table.

**Comment by thetutlage** [comment]
Published as `1.0.3`

**Comment by willvincent** [comment]
Not sure if it's a regression or just an oversight, but this appears to still be an issue in 1.0.5

Looks like PR #26 should resolve.
