### ISSUE TITLE
updatePasswordByToken(token, payload) saves new pass as plainText

### ISSUE THREAD

**Issue by nikos93123** [adonisjs/adonis-persona#6]
In documentation it says updatePasswordByToken updates the user password.

It updates the password of user but saves it as plain text in db.

Why not saves it hashed as doing by default adonis?

**Comment by dmklsv** [comment]
I think it's a bug. After updatePasswordByToken, I can not enter under the new one. I think  at the login, the hash is checked, but this does not happen, because the password is a plain text. #

**Comment by dmklsv** [comment]
My mistake. No, this is not a bug, the password is hashed in another code in the hook (if app create in adonis cli) in app/Models/User.js

Need to replace

```
this.addHook('beforeCreate', async (userInstance) => {
      if (userInstance.password) {
        userInstance.password = await Hash.make(userInstance.password)
      }
    })
```
On this
```
this.addHook('beforeSave', async (userInstance) => {
      if (userInstance.password) {
        userInstance.password = await Hash.make(userInstance.password)
      }
    })
```
And everything worked perfectly
I think it's worth adding to the instructions to the provider Persona

P.S. Hook Explanation:
beforeCreate | Before creating a new row.
afterSave | After a new record has been createdor updated.

**Comment by thetutlage** [comment]
Sure, I will do that

**Comment by insign** [comment]
Sorry but, is it a bug or just not explained in the docs? Maybe I can help, in the meantime I'll use the @dmklsv solution.

**Comment by insign** [comment]
UPDATE: Not sure if it is only with my but the password is re-hashing on any change, like confirming e-mail.

**Comment by dmklsv** [comment]
This is already described in the documentation.

**updatePassword(user,payload)**
Updates the user's password by performing the following steps:

`Make sure to have the beforeSave hook in place for hashing the password. Otherwise the password will be saved as a plain string.`
