### ISSUE TITLE
Validation exception on failed login

### ISSUE THREAD

**Issue by ammezie** [adonisjs/adonis-persona#8]
This is not a bug of some sort, it more of an enhancement. Instead of throwing a validation exception on failed login, maybe throw a generic error of some sort then we can catch and handle the error however we like.

Also, displaying individual error for wrong email and password (can not locate user and password is invalid) on login seem less secured to me.

**Comment by thetutlage** [comment]
> Also, displaying individual error for wrong email and password

You can customize error messages inside `config/persona.js` file.

```js
validationMessages: function (action) {
  return {
    'email.required': action === 'register' ? 'Message A' : 'Message B'
  }
}
```

> Instead of throwing a validation exception on failed login, maybe throw a generic error

How this will help?

**Comment by ammezie** [comment]
> You can customize error messages inside `config/persona.js` file.

I'm aware. It not about the error message itself. I'm concerned about displaying them.

Why I said less secured: for instance, someone trying to log in to a random user's account with email and password. See a message like `password is invalid` tells him at least he got the email right, all that is left is to crack the password.

But displaying a generic message like `Invalid email or password` at login makes it harder to tell which is wrong between the combinations, which I think is more secure.

> How this will help?

It will in my explanation above and moreover, at this point, I believe the user has already passed validation.

**Comment by RomainLanz** [comment]
I'm personally using an `InvalidCredentialException` exception that shows whenever the uid is wrong or the password.

The same thing should be done for `Forget my Password`, whenever the user/email exists or not you should display that an email has been sent to X.

**Comment by thetutlage** [comment]
You can simply have a generic message for both email and password, and hence user has no idea what is wrong.

**Comment by thetutlage** [comment]
Closing since not actionable
