### ISSUE TITLE
Sugestion uuid

### ISSUE THREAD

**Issue by danielsalles** [adonisjs/adonis-persona#9]
Using complex token, does not allow me to make use of in the url.

Example: `updatepassword/9ab5e3150e712f27d259c6965003581fWuV6rvLY+b7CGb/JaJ3gRPIefVFvdI5tjSI+IoUXsRU=`

ps: this hash has **/**

result:
`"message": "Route not found POST /requestforgotpassword/9ab5e3150e712f27d259c6965003581fWuV6rvLY+b7CGb/JaJ3gRPIefVFvdI5tjSI+IoUXsRU=",
`

code:
```javascript
Route
  .post('/updatepassword/:token', 'User/TokenController.changePassword')
  .validator('User/forgotpassword')
```

https://www.npmjs.com/package/uuid resolve this problem

**Comment by ammezie** [comment]
@danielsalles you will need to encode the token before sending it as URL in an email.

The README mention this:
> Make sure to use `querystring` module to encode the token when sending via Email.

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
